### ISSUE TITLE
Msi Ps42 8ra

### ISSUE THREAD

**Issue by constantineoo** [JokerAB/Mechrevo-S1-Hackintosh#1]
Hi. This efi is very nice but there are some problems. When held, it slows down the performance of the mouse and the order sometimes blinks. Can I ask you for an EFi answer to work well. I will be very grateful

**Comment by JokerAB** [comment]
I am sorry,I haven't done any tests on MSI, could you please give me your contact information

**Comment by constantineoo** [comment]
Sure. My email: ludojad1986@gmail.com
I got your EFI from a friend and installed MacOs correctly. however, a complaint about the above-mentioned problems. No resurrection after kext update and image flashes sometimes. I will be very grateful to adjust OC 0.6.4 to the configuration.

My configuration:
Msi Ps42 8RA

I have configuration:

i5 8265U
16GB RAM
Ssd: samsung 970 evo plus nvme
intel HD 620
Nvidia mx 250 - not work i know
Network: Intel Wireless AC 9560

**Comment by JokerAB** [comment]
Do you have other social media accounts, such as Telegram? I don't often use email

**Comment by constantineoo** [comment]
I creating account but i dont know what i invite y my numer 48 660650636
